import Head from 'next/head'
import { useRouter } from 'next/router'
import { Button } from 'components'

export default function Router1() {
  const router = useRouter()
  const { query, pathname } = router || {}
  const { id } = query || {};

  return (
    <div>
      <Head>
        <title>Router 1</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <center>
          <h1>Router 1</h1>

          <div>Pathname: {pathname}</div>
          <div>Id: {id}</div>

          <Button type="button" onClick={() => router.back()}>
            Back Router
          </Button>
        </center>
      </div>
    </div>
  )
}
