import Head from 'next/head'
import { API_POST } from 'constants/apiPath'
import { getUrl } from 'utils'
import styles from './styles.module.scss'
import { Button, Container, DataNotFound, HeaderAction } from 'components';
import { useRouter } from 'next/router';
import { ROUTER_PATH } from 'constants/routerPath';

export default function DetailPost({ data, id }) {
  const { title = 'Title', content = 'Content' } = data || {};

  const router = useRouter();

  const handleEditPost = () => {
    router.push({
      pathname: ROUTER_PATH.CREATE_POST,
      query: {
        id
      }
    })
  }

  return (
    <div>
      <Head>
        <title>Detail Post</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <HeaderAction title='Detail Post'>
          <Button onClick={handleEditPost} disabled={!data}>
            Edit Post
          </Button>
        </HeaderAction>
        {
          data ? (
            <>
              <center><h2>{title}</h2></center>
              <p className={styles.content}>{content}</p>
            </>
          ) : (
            <DataNotFound />
          )
        }
      </Container>
    </div>
  )
}

DetailPost.getInitialProps = async (ctx) => {
  const { query } = ctx;
  const { id } = query || {}
  const path = getUrl(API_POST, ctx) + `?${id}`;

  const res = await fetch(path, {
    method: 'GET',
    headers: { 'Content-Type': 'application/json' },
  });

  const json = await res.json();
  const { data } = json;

  return { data, id };
}
