import Head from 'next/head'
import { useRouter } from 'next/router'
import { ROUTER_PATH } from 'constants/routerPath'
import { Button } from 'components'

export default function Router() {
  const router = useRouter()

  return (
    <div>
      <Head>
        <title>Router</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <center>
          <h1>Router</h1>

          <Button
            type="button"
            onClick={() => {
              router.push({
                pathname: ROUTER_PATH.ROUTER_1,
                query: { id: '1' },
              })
            }}
          >
            Go to Router 1
          </Button>
        </center>
      </div>
    </div>
  )
}
