import Head from 'next/head'
import { Card } from 'components'
import styles from 'styles/Home.module.scss'
import { ROUTER_PATH } from 'constants/routerPath'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <br />

        <div className={styles.grid}>
          {/* <Card href={ROUTER_PATH.HELLO_WORLD} title="Hello World" />

          <Card href={ROUTER_PATH.FETCH_API} title="Fetch API" />

          <Card href={ROUTER_PATH.ROUTER} title="Router" /> */}

          <Card href={ROUTER_PATH.POST} title="POST" />

          <Card href={ROUTER_PATH.POSTS} title="POSTS" />
        </div>
      </main>
    </div>
  )
}